name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: rustup component add clippy
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,just
    - uses: Swatinem/rust-cache@v2
    - run: just build
    - run: just check
    - run: just fmt --check
    - run: just test
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update nightly && rustup default nightly
    - uses: taiki-e/install-action@v2
      with:
        tool: just
    - uses: Swatinem/rust-cache@v2
    - run: just doc
